apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: ubuntu
        command: ["/bin/bash","-c","sleep 100000"]
        name: guestbook-ui
      startupProbe:
        exec:
          command:
            - sleep
            - 5
        failureThreshold: 5
        periodSeconds: 10
